name: "Build iOS"

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Flutter"
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.32.x

      - name: "Flutter Get"
        run: flutter pub get

      - name: "Dart Codegen"
        run: dart run build_runner build --delete-conflicting-outputs

      - name: "Flutter Build"
        run: flutter build ipa --no-codesign

      - name: "Xcode Export"
        run: |
          xcodebuild -exportArchive \
            -archivePath build/ios/archive/Runner.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build/ios/ipa

      - name: "Debug"
        continue-on-error: true
        run: |
          ls -lAh build/ios/
          ls -lAh build/ios/ipa/

      - name: "Upload to Actions"
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ipa
          path: build/ios/ipa/*.ipa
