name: "Build iOS"

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Debug Event"
        continue-on-error: true
        run: |
          echo "pwd: $(pwd)"
          echo "--------------------"
          ls .
          echo "--------------------"

          echo "::group::cat event.json"
          cat "${GITHUB_EVENT_PATH}"
          echo "::endgroup::"

      - name: "Setup Flutter"
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.32.x

      - name: "Flutter Get"
        run: flutter pub get

      - name: "Dart Codegen"
        run: dart run build_runner build --delete-conflicting-outputs

      - name: "Flutter Build"
        run: flutter build ipa --no-codesign

      - name: "Debug 1"
        continue-on-error: true
        run: |
          plutil -p build/ios/archive/Runner.xcarchive/Info.plist || cat build/ios/archive/Runner.xcarchive/Info.plist
          echo "----------"
          plutil -p build/ios/archive/Runner.xcarchive/Info.plist | grep Team

      - name: "Xcode Export"
        run: |
          cp ExportOptions.plist build/ios/archive/
          xcodebuild -exportArchive \
            -archivePath build/ios/archive/Runner.xcarchive \
            -exportOptionsPlist build/ios/archive/ExportOptions.plist \
            -exportPath build/ios/ipa

      - name: "Debug 2"
        continue-on-error: true
        run: |
          ls -lAh build/ios/
          ls -lAh build/ios/ipa/

      - name: "Upload to Actions"
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ipa
          path: build/ios/ipa/*.ipa
